### ISSUE TITLE
Layout improvements for the visitor page

### ISSUE THREAD

**Issue by fernandezmanuel** [Refalm/QDVisitorReception#9]
I would like to add this template for the visitor form layout
https://mehedi61.github.io/Login-Signup-form/signup.html

<img width="959" alt="visitor" src="https://user-images.githubusercontent.com/18325865/62835891-6a077500-bc2b-11e9-9962-72d5688ca611.png">

**Comment by Refalm** [comment]
That form doesn't have
`type="email"`
in the "input" tag, the form I made actually does. It makes the webbrowser do the check if what you filled in at the e-mail field resembles an e-mail address, and all that without a line of JavaScript.

Also, that form by mehedi61 is pretty fluffy pointing to various CDN's, which I don't particularly like. Looks pretty nice though, but I'd rather concentrate on making stuff work right now, and focus on making this project look pretty later.

**Comment by fernandezmanuel** [comment]
Np, his code was completely modified, I just need to push it to my repo. Let me know if you need it later on :)
